{
 "title": "H3C_AC",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Job", "query": { "query": "label_values(sysUpTime,job)" } },
   {
    "name": "IP",
    "query": {
     "query": "label_values(sysUpTime,instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(ifHCOutOctets{job=\"$Job\",instance=\"$IP\"})"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "AP信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AP实时在线终端",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cDot11CurrAPStationAssocCount{job=\"$Job\", instance=\"$IP\"}",
     "legendFormat": "{{hh3cDot11APTemplateNameOfAP}}"
    }
   ]
  },
  {
   "title": "AP在线状态",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hh3cDot11APSysUpTime2{job=\"$Job\", instance=\"$IP\"} / 100",
     "legendFormat": "{{hh3cDot11APTemplateNameOfAP}}"
    }
   ]
  },
  {
   "title": "AP CPU实时利用率",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cDot11APCPURTUsage2{job=\"$Job\", instance=\"$IP\"}",
     "legendFormat": "{{hh3cDot11APTemplateNameOfAP}}"
    }
   ]
  },
  {
   "title": "AP 内存实时利用率",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cDot11APMemRTUsage2{job=\"$Job\", instance=\"$IP\"}",
     "legendFormat": "{{hh3cDot11APTemplateNameOfAP}}"
    }
   ]
  },
  { "title": "AC信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "AC在线时长",
   "type": "gauge",
   "description": "描述AC启动时长",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$IP\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC CPU利用率",
   "type": "timeseries",
   "description": "AC的CPU实时利用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "hh3cEntityExtCpuUsage{job=\"$Job\",instance=\"$IP\",hh3cEntityExtPhysicalIndex=\"97\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "AC内存利用率",
   "type": "timeseries",
   "description": "AC的内存实时利用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hh3cEntityExtMemUsage{job=\"$Job\",instance=\"$IP\",hh3cEntityExtPhysicalIndex=\"97\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "实时在线终端数",
   "type": "timeseries",
   "description": "当前所有AP在线终端总数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "hh3cDot11StationConnectCount{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "AP在线数",
   "type": "stat",
   "description": "当前AC连接的AP总数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cDot11APConnectCount{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "AC上联口-下行/上行",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$IP\",ifDescr=~\"GigabitEthernet1/0/4\"}[$__range])",
     "legendFormat": "{{ifDescr}} - 下行"
    },
    {
     "expr": "-irate(ifHCOutOctets{job=\"$Job\",instance=\"$IP\",ifDescr=~\"GigabitEthernet1/0/4\"}[$__range])",
     "legendFormat": "{{ifDescr}} - 上行"
    }
   ]
  }
 ]
}