{
 "title": "锐捷无线控制器-test",
 "description": "华为无线控制器设备",
 "tags": [
  "prometheus",
  "huawei",
  "ac6000"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "label": "Job",
    "query": {
     "query": "label_values(ruijieAcStaNum,job)"
    }
   },
   {
    "name": "IP",
    "label": "无线控制器IP",
    "query": {
     "query": "label_values(ruijieAcStaNum,instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "ifHCOutOctets{job=~\"$Job\",instance=~\"$IP\"}"
    }
   },
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values({job=\"$Job\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "无线办公区AP在线情况",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralApName=~\"JB.*\",ruijieApGeneralState=\"1\"})",
     "legendFormat": "{{instance}}办公教学区在线AP"
    },
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralApName=~\"JB.*\"})",
     "legendFormat": "{{instance}}办公教学区AP总数"
    },
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralApName=~\"JB.*\",ruijieApGeneralState=\"1\"}) / count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralApName=~\"JB.*\"})",
     "legendFormat": "{{instance}}办公教学区AP在线率"
    }
   ]
  },
  {
   "title": "宿舍区无线AP在线情况",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralApName=~\".*XS.*|.*SS.*\",ruijieApGeneralState=\"1\"})",
     "legendFormat": "{{instance}}学生宿舍区在线AP"
    },
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralApName=~\".*XS.*|.*SS.*\"})",
     "legendFormat": "{{instance}}学生宿舍区AP总数"
    },
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralApName=~\".*XS.*|.*SS.*\",ruijieApGeneralState=\"1\"}) / count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralApName=~\".*XS.*|.*SS.*\"})",
     "legendFormat": "{{instance}}学生宿舍区AP在线率"
    }
   ]
  },
  {
   "title": "总览",
   "type": "gauge",
   "description": "不包含微AP,微AP视为主AP的一部分",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralState=\"1\"})",
     "legendFormat": "{{instance}}在线AP数"
    },
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\"})",
     "legendFormat": "{{instance}}AP总数"
    },
    {
     "expr": "count (ruijieApGeneralIp{job=~\"$Job\",ruijieApGeneralState=\"1\"})/ count (ruijieApGeneralIp{job=~\"$Job\"})",
     "legendFormat": "{{instance}}AP在线率"
    }
   ]
  },
  {
   "title": "终端在线数量",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\",ruijieApApName=~'.*NH.*'})",
     "legendFormat": "{{instance}}南湖"
    },
    {
     "expr": "sum (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\",ruijieApApName=~'.*JH.*'})",
     "legendFormat": "{{instance}}鉴湖"
    },
    {
     "expr": "sum (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\",ruijieApApName=~'.*JB.*'})",
     "legendFormat": "{{instance}}办公教学区"
    },
    {
     "expr": "sum (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\",ruijieApApName=~'.*XS.*|.*SS.*'})",
     "legendFormat": "{{instance}}学生宿舍"
    },
    {
     "expr": "sum (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\"})",
     "legendFormat": "{{instance}}在线总人数"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\",ruijieApApName=~'.*NH.*'})",
     "legendFormat": "{{instance}}南湖"
    },
    {
     "expr": "count (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\",ruijieApApName=~'.*JH.*'})",
     "legendFormat": "{{instance}}鉴湖"
    },
    {
     "expr": "count (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\",ruijieApApName=~'.*JB.*'})",
     "legendFormat": "{{instance}}教学办公"
    },
    {
     "expr": "count (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\",ruijieApApName=~'.*XS.*|.*SS.*'})",
     "legendFormat": "{{instance}}学生宿舍"
    },
    {
     "expr": "count (ruijieApStaNum{job=~\"$Job\",ruijieApState=\"1\"})",
     "legendFormat": "{{instance}}在线AP总数"
    }
   ]
  },
  {
   "title": "锐捷南湖老宿舍,微AP状态",
   "type": "table",
   "description": "锐捷智分无线AP",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "ruijieApMicroApBoard{job=~\"$Job\",ruijieApMicroApName=~'.*VAP.*'}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AP核心信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "AP实时在线终端-TOP20",
   "type": "gauge",
   "description": "AP上承载的终端数量",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sort_desc(ruijieApStaNum{job=~\"$Job\", hostname=~\"$Hostname\"}))",
     "legendFormat": "{{ruijieApApName}}"
    }
   ]
  },
  {
   "title": "AP在线状态",
   "type": "table",
   "description": "AP的状态和在线时长",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "ruijieApGeneralMacAddr{job=~\"$Job\", instance=~\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AP实时CPU利用率-TOP20",
   "type": "gauge",
   "description": "AP实时CPU利用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sort_desc(ruijieSystemApCPUUtilizationCurrent{job=~\"$Job\",hostname=~\"$Hostname\"}))",
     "legendFormat": "{{ruijieApApName}}"
    }
   ]
  },
  {
   "title": "AP内存使用率-TOP20",
   "type": "gauge",
   "description": "AP内存使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sort_desc(ruijieSystemApMemoryPoolCurrentUtilization{job=~\"$Job\", hostname=~\"$Hostname\"}))",
     "legendFormat": "{{ruijieApApName}}"
    }
   ]
  },
  { "title": "AC核心信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "无线控制器名",
   "type": "stat",
   "description": "无线控制器名称",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysName{job=~\"$Job\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "description": "CPU使用率展示",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruijieCPUUtilization1Min {hostname=~\"$Hostname\"} > 0",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "description": "内存使用率展示",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruijieMemoryPoolCurrentUtilization{hostname=~\"$Hostname\"} > 0",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "设备温度",
   "type": "gauge",
   "description": "设备温度展示",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hwEntityTemperature{instance=~\"$IP\"} < 100",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "启动时长",
   "type": "stat",
   "description": "AC启动时长",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruijieSystemUptime {hostname=~\"$Hostname\"} > 0",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{instance=~\"$IP\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{instance=~\"$IP\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{instance=~\"$IP\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{instance=~\"$IP\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "上行 / 下行-指定接口",
   "type": "graph",
   "description": "接口上下行流量变化",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=~\"$Job\",instance=~\"$IP\",ifAlias=~\"To.*\"}[$__range])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCOutOctets{job=~\"$Job\",instance=~\"$IP\",ifAlias=~\"To.*\"}[$__range])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    }
   ]
  }
 ]
}