{
 "title": "交换机通用监控",
 "description": "For snmp_exporter IF-MIB",
 "tags": [
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "IP",
    "label": "instance",
    "query": {
     "query": "sysName{job=\"$Job\"}"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "ifHCOutOctets{job=\"$Job\",instance=\"$IP\"}"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "交换机基本信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "交换机名",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sysName{instance=\"$IP\",job=\"$Job\"}",
     "legendFormat": "{{sysName}}"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hwEntityUpTime{instance=\"$IP\",job=\"$Job\"} > 0",
     "legendFormat": "{{entPhysicalIndex}}"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "指定接口流量和-5分钟",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out / In-指定接口",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-irate(ifHCOutOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$IP\",ifName=~\"$Interface\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "所有接口",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\",instance=\"$IP\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$IP\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\",instance=\"$IP\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\",instance=\"$IP\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 100MB  \nRed Status: 90MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$IP\",job=\"$Job\"}[5m])>0",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 100MB  \nRed Status: 90MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=\"$IP\",job=\"$Job\"}[5m])>0",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "-irate(ifHCOutOctets{instance=\"$IP\",job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInOctets{instance=\"$IP\",job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  }
 ]
}