{
 "title": "华为无线AC&AP监控",
 "description": "华为无线控制器设备",
 "tags": [
  "prometheus",
  "huawei",
  "ac6000"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(hwWlanIDIndexedApOnlineUserNum,  job)"
    }
   },
   {
    "name": "IP",
    "label": "无线控制器IP",
    "query": {
     "query": "label_values(hwWlanIDIndexedApOnlineUserNum, instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "ifHCOutOctets{job=\"$Job\",instance=\"$IP\"}"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "AP核心信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "上行数据变化",
   "type": "timeseries",
   "description": "发送的数据总量变化情况",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(hwWlanIDIndexedApUpPortSendBytes{job=\"$Job\", instance=\"$IP\"}[$__range])",
     "legendFormat": "{{hwWlanIDIndexedApName}}"
    }
   ]
  },
  {
   "title": "下行数据量变化趋势",
   "type": "timeseries",
   "description": "AP接收数据的变化情况",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(hwWlanIDIndexedApUpPortRecvBytes{job=\"$Job\", instance=\"$IP\"}[$__range])",
     "legendFormat": "{{hwWlanIDIndexedApName}}"
    }
   ]
  },
  {
   "title": "AP实时温度-TOP20",
   "type": "gauge",
   "description": "AP的实时温度监控",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sort_desc(hwWlanIDIndexedApTemperature{job=\"$Job\", instance=\"$IP\"}))",
     "legendFormat": "{{hwWlanIDIndexedApName}}"
    }
   ]
  },
  {
   "title": "AP实时在线终端-TOP20",
   "type": "gauge",
   "description": "AP上承载的终端数量",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sort_desc(hwWlanIDIndexedApOnlineUserNum{job=\"$Job\", instance=\"$IP\"}))",
     "legendFormat": "{{hwWlanIDIndexedApName}}"
    }
   ]
  },
  {
   "title": "AP在线状态",
   "type": "table",
   "description": "AP的状态和在线时长",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hwWlanIDIndexedApOnlineTime{job=\"$Job\", instance=\"$IP\"}",
     "legendFormat": "{{hwWlanIDIndexedApName}}"
    }
   ]
  },
  {
   "title": "AP实时CPU利用率-TOP20",
   "type": "gauge",
   "description": "AP实时CPU利用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sort_desc(hwWlanIDIndexedApCpuUseRate{job=\"$Job\", instance=\"$IP\"}))",
     "legendFormat": "{{hwWlanIDIndexedApName}}"
    }
   ]
  },
  {
   "title": "AP内存使用率-TOP20",
   "type": "gauge",
   "description": "AP内存使用率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sort_desc(hwWlanIDIndexedApMemoryUseRate{job=\"$Job\", instance=\"$IP\"}))",
     "legendFormat": "{{hwWlanIDIndexedApName}}"
    }
   ]
  },
  {
   "title": "AC核心信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "无线控制器名",
     "type": "stat",
     "description": "无线控制器名称",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sysName{job=\"$Job\", instance=\"$IP\"}",
       "legendFormat": "{{sysName}}"
      }
     ]
    },
    {
     "title": "内存使用率",
     "type": "gauge",
     "description": "内存使用率展示",
     "gridPos": { "h": 3, "w": 4, "x": 7, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hwEntityMemUsage{instance=\"$IP\"} > 0",
       "legendFormat": "Mem"
      }
     ]
    },
    {
     "title": "CPU使用率",
     "type": "gauge",
     "description": "CPU使用率展示",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hwEntityCpuUsage{instance=\"$IP\"} > 0",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "设备温度",
     "type": "gauge",
     "description": "设备温度展示",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hwEntityTemperature{instance=\"$IP\"} < 100",
       "legendFormat": "Temperature"
      }
     ]
    },
    {
     "title": "启动时长",
     "type": "stat",
     "description": "AC启动时长",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hwEntityUpTime{instance=\"$IP\"} > 0",
       "legendFormat": "In"
      }
     ]
    },
    {
     "title": "Total Out",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(delta(ifHCOutOctets{instance=\"$IP\"}[$__range]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Total In",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(delta(ifHCInOctets{instance=\"$IP\"}[$__range]))",
       "legendFormat": "In"
      }
     ]
    },
    {
     "title": "Max Out (Current)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 11, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(irate(ifHCOutOctets{instance=\"$IP\"}[$__range]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Max In (Current)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(irate(ifHCInOctets{instance=\"$IP\"}[$__range]))",
       "legendFormat": "In"
      }
     ]
    },
    {
     "title": "上行 / 下行-指定接口",
     "type": "graph",
     "description": "接口上下行流量变化",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$IP\",ifDescr=~\"$Interface\"}[$__range])",
       "legendFormat": "In: {{ifName}} ({{ifAlias}})"
      },
      {
       "expr": "-irate(ifHCOutOctets{job=\"$Job\",instance=\"$IP\",ifDescr=~\"$Interface\"}[$__range])",
       "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
      }
     ]
    }
   ]
  }
 ]
}