{
 "title": "深信服AD",
 "description": "深信服AD监控",
 "tags": [
  "sangfor",
  "snmp",
  "ad"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(adLinkBitIn,  job)"
    }
   },
   { "name": "IP", "label": "设备IP", "query": { "query": "label_values(adConns,instance)" } },
   {
    "name": "Interface",
    "label": "链路接口",
    "query": {
     "query": "adLinkBitIn{job=\"$Job\",instance=\"$IP\"}"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "设备名称",
   "type": "stat",
   "description": "设备名称",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adSysName{job=\"$Job\", instance=\"$IP\"}",
     "legendFormat": "{{adSysName}}"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "description": "CPU使用率展示",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adCpuCostRate{instance=\"$IP\"} > 0",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "description": "内存使用率展示",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adMemCostRate{instance=\"$IP\"} > 0",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "description": "磁盘使用率展示",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adDiskCostRate{instance=\"$IP\"} > 0",
     "legendFormat": "Mem"
    }
   ]
  },
  {
   "title": "设备温度",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sfIntCpuTemp{instance=\"$IP\"} > 0",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "磁盘温度",
   "type": "gauge",
   "description": "磁盘温度展示",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sfDiskTemp{instance=\"$IP\", diskIndex=\"1\"} > 0",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "stat",
   "description": "深信服AD启动天数",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adUptime{instance=\"$IP\"}",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "所有链路上行流量(当前)",
   "type": "stat",
   "description": "所有链路上行流量(当前)",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adUplinkThroughput{instance=\"$IP\"} * 1024",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "所有链路下行流量(当前)",
   "type": "stat",
   "description": "所有链路下行流量(当前)",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adDownlinkThroughput{instance=\"$IP\"} * 1024",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "系统并发连接数",
   "type": "stat",
   "description": "系统并发连接数",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adConns{job=~\"$Job\", instance=~\"$IP\"}"
    }
   ]
  },
  {
   "title": "新建并发连接数",
   "type": "stat",
   "description": "新建并发连接数",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adNewConns{job=~\"$Job\", instance=~\"$IP\"}"
    }
   ]
  },
  {
   "title": "AD运行模式",
   "type": "stat",
   "description": "AD运行模式",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adDevicePattern{job=~\"$Job\", instance=~\"$IP\"}",
     "legendFormat": "主备模式"
    }
   ]
  },
  {
   "title": "设备状态",
   "type": "stat",
   "description": "设备状态",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sfDeviceStatus{job=\"$Job\", instance=\"$IP\"} == 1",
     "legendFormat": "设备状态"
    }
   ]
  },
  {
   "title": "双机主备状态",
   "type": "stat",
   "description": "双机主备状态",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adStandByState{job=\"$Job\", instance=\"$IP\"} == 1",
     "legendFormat": "双机主备状态"
    }
   ]
  },
  {
   "title": "风扇状态",
   "type": "stat",
   "description": "风扇状态",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sfFanState{job=\"$Job\", instance=\"$IP\", fanIndex=\"1\"} == 1",
     "legendFormat": "风扇{{fanIndex}}"
    },
    {
     "expr": "sfFanState{job=\"$Job\", instance=\"$IP\", fanIndex=\"2\"} == 1",
     "legendFormat": "风扇{{fanIndex}}"
    },
    {
     "expr": "sfFanState{job=\"$Job\", instance=\"$IP\", fanIndex=\"3\"} == 1",
     "legendFormat": "风扇{{fanIndex}}"
    }
   ]
  },
  {
   "title": "风扇转速",
   "type": "stat",
   "description": "风扇转速",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sfFanSpeed{job=\"$Job\", instance=\"$IP\", fanIndex=\"1\"}",
     "legendFormat": "风扇{{fanIndex}}"
    },
    {
     "expr": "sfFanSpeed{job=\"$Job\", instance=\"$IP\", fanIndex=\"2\"}",
     "legendFormat": "风扇{{fanIndex}}"
    },
    {
     "expr": "sfFanSpeed{job=\"$Job\", instance=\"$IP\", fanIndex=\"3\"}",
     "legendFormat": "风扇{{fanIndex}}"
    }
   ]
  },
  {
   "title": "上行 / 下行-指定接口",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "adLinkBitOut{job=\"$Job\",instance=\"$IP\",adLinkName=~\"$Interface\"}",
     "legendFormat": "下行: {{adLinkIfName}} ({{adLinkName}})"
    },
    {
     "expr": "adLinkBitIn{job=\"$Job\",instance=\"$IP\",adLinkName=~\"$Interface\"}",
     "legendFormat": "上行: {{adLinkIfName}} ({{adLinkName}})"
    }
   ]
  },
  {
   "title": "上行 / 下行-所有接口",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "adLinkBitOut{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "下行: {{adLinkIfName}} ({{adLinkName}})"
    },
    {
     "expr": "adLinkBitIn{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "上行: {{adLinkIfName}} ({{adLinkName}})"
    }
   ]
  },
  {
   "title": "上行流量  (当前)",
   "type": "bargauge",
   "description": "上行流量  (当前)  根据查询时间定义",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adLinkBitIn{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "上行: ({{adLinkName}})"
    }
   ]
  },
  {
   "title": "下行流量 (当前)",
   "type": "bargauge",
   "description": "下行流量 (当前)  根据查询区间变化",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adLinkBitOut{job=\"$Job\",instance=\"$IP\"}",
     "legendFormat": "下行: ({{adLinkName}})"
    }
   ]
  }
 ]
}